# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  unit_test:
    docker:
      - image: circleci/node:12.14.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test:unit

  e2e_test:
    docker:
      - image: circleci/node:12.14.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test:e2e

  build_for_windows:
    executor: win/default
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm i -g yarn
      - run: yarn install
      - run: yarn build --win
      - run:
          command: mkdir -p workspace/dist/windows
          shell: bash
      - run:
          command: mv dist_electron workspace/dist/windows
          shell: bash
      - persist_to_workspace:
          root: workspace
          paths:
            - dist

  build_for_linux:
    docker:
      - image: circleci/node:12.14.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - run: yarn build
      - run: mkdir -p workspace/dist/linux
      - run: mv dist_electron workspace/dist/linux
      - persist_to_workspace:
          root: workspace
          paths:
            - dist

  deploy:
    docker:
      - image: cibuilds/github:0.10
    working_directory: ~/build
    steps:
      - attach_workspace:
          at: workspace
      - run: ls workspace/dist/windows/dist_electron
      - run: ls workspace/dist/linux/dist_electron
workflows:
  version: 2

  standard_workflow:
    jobs:
      - unit_test:
          filters:
            tags:
              only: /.*/
      - e2e_test:
          filters:
            tags:
              only: /.*/
      - build_for_windows:
          requires:
            - unit_test
            - e2e_test
          filters:
            tags:
              only: /.*/
      - build_for_linux:
          requires:
            - unit_test
            - e2e_test
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build_for_windows
            - build_for_linux
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
