name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install npm packages
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: Build the project
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build
    - name: Rub unit tests
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: test:unit
